### ISSUE TITLE
accounts-ui dependency

### ISSUE THREAD

**Issue by benjick** [artwells/meteor-accounts-guest#29]
Does this need to exist? I would want to use `ian:accounts-ui-bootstrap-3` instead of `accounts-ui`

**Comment by artwells** [comment]
I imagine that other accounts-ui packages would work as well.  accounts-ui is the only one that's been tested, and one is required.

**Comment by benjick** [comment]
Since `accounts-ui` is included, I can't include `ian:accounts-ui-bootstrap-3`.

But I ended up building my own login anyways

**Comment by jbrozena22** [comment]
I ran into the same issue. I had been using ian:accounts-ui-bootstrap-3. With the latest update of this package I get this: "Error: There are multiple templates named '_loginButtonsLoggedIn' ". Because my project now includes accounts-ui and ian:accounts-ui-bootstrap-3. Long story short, my login buttons now are unstyled and will need to be custom built to work with your package...

**Comment by artwells** [comment]
I've removed the dependency and updated the README to include instructions
https://github.com/artwells/meteor-accounts-guest/releases/tag/0.1.12

**Comment by jbrozena22** [comment]
Thanks for the quick action and for the awesome package!
